Maestro User Docs Updates
overture-stack/website pull request #264
Opened 2023-07-10 18:48 UTC by MitchellShiell

## Maestro Docs Updates 

- Docker image required
- Managing Index mapping needs expanding
- Add image
- See comment on Slack integration page [line 12]

site map

<img width="376" alt="Screenshot 2023-07-10 at 2 47 35 PM" src="https://github.com/overture-stack/website/assets/59712867/1fd6ac83-c216-4aa5-8d65-806fd30517b1">

2023-12-18 18:42 UTC, MitchellShiell commented
@leoraba Along with the general review, take a look at the prereq page, it's a bit vague, you can leave a comment on any information you feel is missing or could add to the explanation of Kafka (what it is, and why we use it)

2023-12-20 19:34 UTC, leoraba requested changes

2023-12-20 20:17 UTC, MitchellShiell commented on markdown/documentation/maestro/admin-guide/mappings.md
> +For example, when updating Songs' <a href="/documentation/song/user-guide/schema/" target="_blank" rel="noopener noreferrer">dynamic schemas</a> the administrator must also update Maestros' index map
Good catch, this formatting works in local but not live, I'll double check all links and update them

2023-12-20 20:20 UTC, MitchellShiell commented on markdown/documentation/maestro/installation/configuration/index.md
> +- [Elasticsearch](/documentation/score/installation/configuration/profiles): 	Set the index mapping and configure connection parameters and error handling mechanisms.
Weird, I'll check all links and update

2023-12-22 12:42 UTC, leoraba approved these changes
Looks good. Thanks!

2024-01-02 14:24 UTC, merged