Style/#229 landing page lower grey section css
overture-stack/website pull request #284
Opened 2023-08-10 15:29 UTC by daniel-cy-lu

Lower grey section and footer responsive css completed.

2023-08-17 15:14 UTC, daniel-cy-lu commented
@ciaranschutte @mistryrn Hi guys, usually Sam helps me review these responsive css, but she has a new assignment and @joneubank suggested that I tag you. For this ticket, I completed the lower grey section in the home/landing page of overture. I provided a link to the mock up in the description. Thank you for your help as always! :D

2023-08-21 15:17 UTC, ciaranschutte requested changes
two small changes.
I tested it out locally, looking really good @daniel-cy-lu - responsiveness is great!

2023-08-21 15:17 UTC, ciaranschutte commented on src/components/Footer/index.js
> +        <Link className="links-container__link" to={link.url}>
you need to put a `key` prop in these links so React can reconcile its renders.
fixes this error:

![Screenshot 2023-08-21 at 11 15 29 AM](https://github.com/overture-stack/website/assets/1486054/af530272-ed6d-4ae0-b8a8-51829b6102c7)

2023-08-21 15:17 UTC, ciaranschutte commented on src/components/Footer/styles.scss
> +        // width: auto;
this is not doing anything because it's commented out. can remove whole `@include` segment

2023-08-21 15:35 UTC, daniel-cy-lu commented on src/components/Footer/index.js
> +        <Link className="links-container__link" to={link.url}>
I will take a look, thanks Ciaran! didn't see this before.

2023-08-21 15:40 UTC, daniel-cy-lu commented on src/components/Footer/styles.scss
> +        // width: auto;
removed used css

2023-08-22 06:06 UTC, ciaranschutte commented on src/components/Footer/index.js
> +        <Link className="links-container__link" to={link.url}>
I don't see an error in the screenshot? is it the yellow underline? 
These would likely be TS errors. Check to see if an error appears in the console of the browser please.

best practice to at least do:
```
{links.map((link, index) => <Link key={index} ...other code/>
```
or some always unique part of the data

more info can be found here: https://react.dev/learn/rendering-lists

2023-08-22 14:37 UTC, ciaranschutte commented on src/components/Footer/index.js
> +        <Link className="links-container__link" to={link.url}>
just double checked console - should be ok to add a key to resolve error - let me know if there's still an issue

2023-08-22 15:32 UTC, daniel-cy-lu commented on src/components/Footer/index.js
> +        <Link className="links-container__link" to={link.url}>
Thanks Ciaran for showing the best practice. I add index to the map method in <FooterLink> and all the error in your initial screenshot went away! 

I thought I had to go and find each <Link> and add the key! :)

2023-08-28 19:06 UTC, merged

2023-08-28 19:18 UTC, daniel-cy-lu commented
@joneubank Thanks Jon