Song userdocs update
overture-stack/website pull request #295
Opened 2023-08-18 17:27 UTC by MitchellShiell

# Major Update
<img align="left" width="205" alt="Screenshot 2023-08-18 at 1 04 01 PM" src="https://github.com/overture-stack/website/assets/59712867/6731140d-583b-45d7-aaa5-63562c384c28">

## Update Overview

- New intro page with illustration
- Separate Prerequisites page
- Updated installation page via Docker
- Updated Configurations section/pages in line with the docker environment variable file installation 
- New User Guide Content (In collaboration with Edmund and Linda)
    - updated to API Usage, including Retrieving and Updating Metadata through Swagger as well as more advanced programmatic queries with examples
- New Admin Guide Section, including
    -  An intro page to dynamic schemas
    - Separate pages covering Making, Registering and Managing Schemas 
    - Updated Analysis Management Page
- New reference section with a song-client command reference page

### Other quality of life additions:

- All links now open within a new tab instead of removing users from the current page.
- Content written in line with our <a href="https://github.com/overture-stack/.github/wiki/Documentation-Style-Guide"  target="_blank">documentation style guide</a> 

Full Documentation Site Map: https://wiki.oicr.on.ca/display/OV/Overture.bio+Docs+Co-Ordination+Doc

2023-09-22 21:23 UTC, joneubank reviewed
Song Comments.

Will read Score docs next.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/analysismanagement.md
> +- **Published:** The data and analysis are recognized by other downstream processes such as Maestro for metadata and file data indexing. In reverse, going from PUBLISHED to UNPUBLISHED will remove th
This is the typical behaviour. I would accurately describe Published as "The file is available for download from file storage.", score will not allow unpublished and suppressed files to be downloaded, and song will not allow you to publish if the file does not exist in storage.

It is also possible to configure Maestro to index unpublished and suppressed files so peopel can see what analyses are awaiting file upload (unpublished) or have been made unavailable. Indexing these is not the default behaviour and requires custom configuration.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/analysismanagement.md
> +<Note title="Removing Indexed Data"> To ensure safe removal of indexed data the suggested state transition for suppression is: Published → Unpublished → Suppressed.</Note>
I'm not sure if this is necessary or why. Do you know where this came from?

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/schemas/index.md
> +Song utilizes <a href="https://json-schema.org/" target="_blank" rel="noopener noreferrer">JSON Schema</a> to validate metadata during submission. Data is submitted to Song in JSON format and undergo
The first two sentences here both say "JSON data is validated by JSON Schema. Maybe the first sentence can be rephrased to say:

Song utilizes JSON Schema to describe the structure of metadata that will be stored for each analysis.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/schemas/index.md
> +In Song, metadata is captured and submitted as **analyses**. An analysis represents a complete metadata record that includes references to the corresponding data files, all grouped as a single JSON o
An analysis represents a collection of one or more files, and includes a complete metadata record describing those files.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/schemas/index.md
> +When submitting an analysis to Song, you need to specify the desired **schema** (data model) to be used for validation. This is defined in your analysis file using the `analysis type` field.
here we are asking for the user to specify the type of analysis they are submitting, ie. is this raw genomic data (sequencing experiment), or the variants file and associated index created from a variant calling analysis. Perhaps this should be phrased as "selecting an analysis type" and that will specify the data model that will be used to validate the analysis metadata.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/schemas/index.md
> +1. A minimal, **base schema** that is defined for patient data.
Base schema includes fields that we require for all analyses, including minimal patient data and submitter IDs, and the file information.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/admin/schemas/index.md
> +2. A flexible **dynamic schema** that is configured and uploaded by a Song administrator.
Custom schemas are configured by song administrator, the purpose is to describe this specific analysis type.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +**Analysis Files:** An Analysis file contains the metadata in a structured JSON format. Metadata gets submitted to Song as an Analysis File.
Analysis is a description of a set of one or more files plus the metadata describing that collection of files.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +**Metadata Validation:** Analysis files get validated against the administrator's Dynamic Schema. That defines the vocabulary and structure of the Analysis File.
analysis document*

one analysis -> one or more files

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +**Metadata Validation:** Analysis files get validated against the administrator's Dynamic Schema. That defines the vocabulary and structure of the Analysis File.
instead of "analysis file is submitted" i would suggest "analysis document is stored"

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +**Metadata Validation:** Analysis files get validated against the administrator's Dynamic Schema. That defines the vocabulary and structure of the Analysis File.
analysis record could also be used. or just analysis. The terminology here should be whatever is clearer to read, but should be consistent throughout.

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +As a metadata management system, Song does not handle file transfer and object storage. Song interacts with a required companion application, <a href="/documentation/score" target="_blank" rel="noope
👍

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +As a metadata management system, Song does not handle file transfer and object storage. Song interacts with a required companion application, <a href="/documentation/score" target="_blank" rel="noope
Should this be stated earlier, that Song works in partnership with Score? Song as the file metadata catalog and Score as the upload/download manager?

2023-09-22 21:23 UTC, joneubank commented on markdown/documentation/song/index.md
> +- **Event Streaming:** Built-in support for <a href="https://kafka.apache.org/" target="_blank" rel="noopener noreferrer">Apache Kafka</a> event streaming.
Allows other services to react when analyses are registered and published.

2023-09-22 21:26 UTC, MitchellShiell commented on markdown/documentation/song/admin/analysismanagement.md
> +<Note title="Removing Indexed Data"> To ensure safe removal of indexed data the suggested state transition for suppression is: Published → Unpublished → Suppressed.</Note>
Edmund if i remeber correctly

2023-09-25 15:46 UTC, MitchellShiell commented on markdown/documentation/song/index.md
> +As a metadata management system, Song does not handle file transfer and object storage. Song interacts with a required companion application, <a href="/documentation/score" target="_blank" rel="noope
👍🏻

2023-10-11 14:27 UTC, joneubank requested changes
Great content, found a handful of nitpicks!

2023-10-11 14:27 UTC, joneubank commented on markdown/documentation/song/installation/configurations/id.md
> +<Warning> You cannot mix and match local/external ID management. Either all IDs are locally managed by Song, or all IDs are managed by external services. </Warning>
I think we can simplify this to:

Two kinds of auth management (Local and Federated).
Federated ID service can have two kinds of auth (dynamic with JWT, static with defined key). Can probably move the auth details into the heading below about federated ID management.

2023-10-11 14:27 UTC, joneubank commented on markdown/documentation/song/installation/configurations/profiles.md
> +To interact with Song, an application must provide authentication and authorization. This can be done by using an API Key from an authorized user with the appropriate permissions or by enabling appli
I think the line about `application-to-application auth following oauth 2.0` isn't correct. Ego provides a mechanism in Ego for applications to fetch a JWT (access token) using Basic Authentication - this isn't strictly an OAuth protocol. Maybe:

> This can be done by using an API Key or JWT access token from a user or application authorized with Ego.

2023-10-11 14:27 UTC, joneubank commented on markdown/documentation/song/installation/configurations/profiles.md
> +- If Ego is used as the authentication method with Song, this profile is required.  The default URL is configured to work with Ego.
Song can only use Ego as an auth provider, so this is always true when `secure` profile is enabled.

2023-10-11 14:27 UTC, joneubank commented on markdown/documentation/song/installation/configurations/profiles.md
> +```
Was reviewing the code to confirm this... Having `secure` profile is all that is needed to also enable JWT auth. The `jwt` profile doesn't change anything anymore. In order for JWTs to work as auth, the `AUTH_JWT_PUBLIC-KEY-URL` env variable must be configured as shown here. This can be added to the `secure` profile description.

2023-10-11 14:27 UTC, joneubank commented on markdown/documentation/song/installation/configurations/profiles.md
> +
We should describe how we integrate with kafka, something like:

When this profile is enabled, Song will send messages to Kafka every time an analysis is created or an analysis is updated. This includes messages when an analysis is published, unpublished or suppressed.

2023-10-11 15:28 UTC, MitchellShiell commented on markdown/documentation/song/admin/analysismanagement.md
> +From the analysis dropdown you can find the `PUT` endpoints for publishing, unpublishing and suppressing analyses. Select your endpoint of interest and click `Try it out`.
text is specifically referencing publishing, unpublishing and suppressing. The image also highlights/outlines the specific endpoints of interest

2023-10-11 15:29 UTC, MitchellShiell commented on markdown/documentation/song/admin/analysismanagement.md
> +2. **Input the Anlysis ID and Credientials**
Good catch these typos are maddening no idea how they slip through

2023-10-11 15:33 UTC, MitchellShiell commented on markdown/documentation/song/admin/analysismanagement.md
> +Input your authorization token and the analysis ID and study ID corresponding to the data you want ot supress.
It isn't needed, but it is better practice will update

2023-10-11 16:17 UTC, MitchellShiell commented on markdown/documentation/song/installation/configurations/profiles.md
> +- If Ego is used as the authentication method with Song, this profile is required.  The default URL is configured to work with Ego.
Not sure what change would be needed here. "Enable secure if using ego, otherwise do not." Can song not be set up using another auth service? Meaning the secure profile + ego is mandatory?

2023-10-12 20:20 UTC, joneubank commented on markdown/documentation/song/admin/analysismanagement.md
> +Input your authorization token  and the analysis ID and study ID corresponding to the data you want to suppress.
weird whitespace (`token  and` with two spaces) but probably gets fixed in html

2023-10-12 20:20 UTC, joneubank approved these changes

2023-10-13 13:37 UTC, merged