Major update
overture-stack/website pull request #306
Opened 2023-08-30 18:59 UTC by MitchellShiell

2023-09-22 22:04 UTC, joneubank commented on markdown/documentation/score/installation/prereq.md
> +Before installing Score, ensure the following software services are installed and running:
We should include an optional entry here for Ego... If they run Score with `secure` profile they will need Ego. I need to validate how score works without this profile, will get back to you on this as I'm having local docker issues with score.

2023-10-17 19:15 UTC, jmimico commented on markdown/documentation/score/installation/configuration/authentication.md
> +Authentication and authorization are crucial to ensuring that unauthorized users don't access Score's API endpoints. To access Score services, users need a valid API key with the appropriate scopes (
Should we replace API key with access token since thats the language thats used in the score-client itself

2023-10-17 19:16 UTC, jmimico commented on markdown/documentation/score/installation/configuration/authentication.md
> +To support both JWT and API Key authentication, use the `jwt` profile. Note that you can't configure JWT as your sole authentication method since Score initially requires an API key. For the `jwt` pr
Should we replace API key with access token since thats the language thats used in the score-client itself

2023-10-17 19:17 UTC, jmimico commented on markdown/documentation/score/installation/configuration/authentication.md
> +To support both JWT and API Key authentication, use the `jwt` profile. Note that you can't configure JWT as your sole authentication method since Score initially requires an API key. For the `jwt` pr
Ignore previous comment, realized this is in the context of a score-server not score-client.

2023-12-07 20:19 UTC, leoraba requested changes
Nice documentation!. just added some comments.

2023-12-07 21:15 UTC, MitchellShiell commented on markdown/documentation/score/installation/configuration/authentication.md
> +| [jwt](#jwt-profile-example) | Optional | Optionally, you can use this profile to support both JWT (<a href="https://jwt.io/" target="_blank" rel="noopener noreferrer">JSON Web Tokens</a>) and API K
noted, will ammend on keycloak docs update

2023-12-07 21:16 UTC, MitchellShiell commented on markdown/documentation/score/installation/configuration/authentication.md
> +| `AUTH_SERVER_TOKEN_NAME`                         | Required    | Name identifying a token. Typically, keep the default value, `token`. |
updated variable names as well

2023-12-11 19:06 UTC, leoraba approved these changes
LGTM 👍

2023-12-11 19:12 UTC, merged